### ISSUE TITLE
Cannot copy directory into place

### ISSUE THREAD

**Issue by pjstadig** [lstoll/heroku-buildpack-monorepo#3]
I've added this to my heroku app, but get the following error when it runs:

> -----> Monorepo app detected
> rm: cannot remove '/app': Read-only file system
>       FAILED to copy directory into place

It looks like previously the app would run `rm -rf ${BUILD}/*`, but now is trying to run `rm -rf ${BUILD}`.

Should it be reverted back to the way it was, or am I doing something wrong in my app?

**Comment by javidjamae** [comment]
Maybe you were having the same problem I encountered recently: https://stackoverflow.com/questions/51449750/how-do-i-get-heroku-ci-to-run-tests-when-using-a-monorepo

This buildpack seems to work fine when you push directly to a Heroku repository, but when you go through the Heroku CI Pipeline, it doesn't seem to work because the filesystem is readonly.

Did you ever figure out a workaround?
